### ISSUE TITLE
Hiding the "status message" collapse

### ISSUE THREAD

**Issue by Tyroie** [WreckedAvent/slimCat#379]
The one that appears in right-click menus. The result is that the status message is just always visible there.

So this is one of the first changes I made when I started fiddling with SlimCat, and I've always re-added it for myself every update. It's always felt so much nicer to me this way, all around. It's pleasing visually to me, and since I pretty much always want to read the status message, it's an irritant to have to go click it. It also makes the tall right-click menu a bit shorter when compared to the opened collapse. Nothing that's actually that important - but for some reason I just really like it more this way.

Any comments that disagree or agree would be good!

**Comment by WreckedAvent** [comment]
How does it look with a max length status?

**Comment by Tyroie** [comment]
Oh actually that's a really good point. They aren't common, but I have seen them.

![Image of a big status message](http://i.imgur.com/NFwrPEs.png)

**Comment by WreckedAvent** [comment]
I can't really let the drop-down get bigger than almost your entire desktop.

If you want this to be in, it'll have to trim an excessively long status. Since they are kind of rare, we shouldn't need anything more than a "more" option somewhere. Hell, you could just move the excessive characters into that status dropdown and only make it show when the status is really long. Sort of like if it was an ad.

**Comment by Tyroie** [comment]
Ah yeah! I was fiddling around a bit, and a scrollbar seems like a nice option, yeah? Made it auto-scroll to top when you re-open the menu.
![Scrollbar Goodness](http://i.imgur.com/NGTnoJ8.png)

**Comment by WreckedAvent** [comment]
That works for me as well.
